name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


  
# defaults:
#   run:
#     working-directory: src

jobs:
  release-and-publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.GITHUB_TOKEN }}