name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write


  
# defaults:
#   run:
#     working-directory: src

jobs:
  release-and-publish-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json